Revert "Fix libsupc++.a(vterminate.o): undefined reference to `_impure_ptr'"
This reverts commit 79d476e4237fbe5dbe09973815f2d53e4624c921.

CXX:  libxx_impure.cxx
libxx_impure.cxx:58:50: error: conflicting declaration '_reent* const _global_impure_ptr'
    struct _reent *const __ATTRIBUTE_IMPURE_PTR__ _global_impure_ptr = &impure_data;
                                                  ^~~~~~~~~~~~~~~~~~
In file included from /Users/yamamoto/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/sys-include/reent.h:93,
                 from libxx_impure.cxx:27:
/Users/yamamoto/.espressif/tools/xtensa-esp32-elf/esp-2020r3-8.4.0/xtensa-esp32-elf/xtensa-esp32-elf/sys-include/sys/reent.h:778:24: note: previous declaration as '_reent* _global_impure_ptr'
 extern struct _reent * _global_impure_ptr __ATTRIBUTE_IMPURE_PTR__;
                        ^~~~~~~~~~~~~~~~~~
make[1]: *** [libxx_impure.o] Error 1
make: *** [libs/libxx/libxx.a] Error 2